language: "en-US"
reviews:
  collapse_walkthrough: true
  sequence_diagrams: false
  tools:
    # Disable eslint and markdown lint
    eslint:
      enabled: false
    markdownlint:
      enabled: false
  path_filters:
    - "!skills/**"
